### ISSUE TITLE
Unsafe encryption algorithms supported

### ISSUE THREAD

**Issue by sveeke** [Coinversable/validana-core#1]
validana-core/src/tools/crypto.ts

Unsafe hash algorithm MD5 and SHA1 are supported - presumably for compatibility. These should be disabled. This class also makes unsafe direct sha1/sha256/sha512 method calls public, while wrapped APIs are available. The direct api calls should be protected or made private.

**Comment by wdenbakker** [comment]
The MD5 and SHA1 hashing algorithms are indeed supported for compatibility. Not because Validana uses it anywhere, but in case legacy applications  need to be integrated with Validana. As such those (and the other hashing methods) are made available inside smart contracts, which is also why they are public.

I understand the preference to disallow this and enforce other applications to use strong security as well and strongly encourage developers to update their legacy applications, however for the sake of compatibility it is allowed.

Also sha256 being public, while hash256 is available, is for example needed in [key.ts](https://github.com/Coinversable/validana-core/blob/master/src/basics/key.ts), where the default library will hash the data once with SHA256, while we wish to hash it once more. Not to mention SHA256 is not inherently unsafe, depending on its application, but double SHA256 is preferred so there is no need to worry about what it is used for and whether security holes are accidental creating created or not.
